obj-$(CONFIG_CHARGER_SC8989X) += sc8989x.o
obj-$(CONFIG_CHARGER_SY697X)    += sy697x.o
obj-$(CONFIG_CHARGER_SGM415XX) += sgm415xx.o
obj-$(CONFIG_CHARGER_SC854X) += sc854x.o
obj-$(CONFIG_CHARGER_PUMP_HL7139) += hl7139_charger.o
obj-$(CONFIG_CHARGER_WT6670F) += wt6670f_charger.o
obj-$(CONFIG_CHARGER_QC_POLICY) += qc_charger_policy.o

ccflags-y += -I$(srctree)/drivers/power/supply
