#obj-$(CONFIG_TOUCHSCREEN_chipone9916) += chipone9916.o
obj-m += chipone9916.o

chipone9916-objs := cts_driver.o
chipone9916-objs += cts_core.o
chipone9916-objs += cts_sfctrlv2.o
chipone9916-objs += cts_spi_flash.o
chipone9916-objs += cts_firmware.o
chipone9916-objs += cts_test.o
chipone9916-objs += cts_charger_detect.o
chipone9916-objs += cts_earjack_detect.o
chipone9916-objs += cts_tcs.o
chipone9916-objs += cts_platform.o
chipone9916-objs += cts_tool.o
chipone9916-objs += cts_sysfs.o
chipone9916-objs += cts_strerror.o
chipone9916-objs += cts_oem.o

